---
title: "Visualization with ggplot2"
author: "Shengzhi Luo"
date: "05/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggridges)
library(patchwork)
library(viridis)

```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_df
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

Start
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  )
```
## Scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  )+
  scale_x_continuous(
    breaks = c(-15,0,15),
    labels = c("-15 C","0","15")
  )+
  scale_y_continuous(
    trans = "sqrt",
    position="right"
  )
```



```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  )+
  scale_color_hue(
    name="Location",
    h=c(100,200))+
  scale_color_viridis_d()
  
  
```

## Themes

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  )+
  scale_color_viridis_d()+
  theme_bw()+
  theme(legend.position="bottom")
```

order of theme

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  )+
  scale_color_viridis_d()+
  theme(legend.position="bottom")+
  theme_bw()
  
```


```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  )+
  scale_color_viridis_d()+
  theme_minimal()+
  theme(legend.position="bottom")
```

## `data` in geoms

```{r}
central_park=
  weather_df %>%
  filter(name=="CentralPark_NY")
waikiki=
  weather_df %>%
  filter(name=="Waikiki_HA")
waikiki %>% 
  ggplot(aes(x = date, y = tmax,color=name)) + 
  geom_point() +
  geom_line(data=central_park)
  
```
## `patchwork`

```{r}
ggp_tmax_tmin=
  weather_df%>%
  ggplot(aes(x = tmin, y = tmax,color=name))+
  geom_point(alpha=0.3)+
  theme(legend.position="none")
ggp_prcp_dens=
  weather_df%>%
  filter(prcp>0)%>%
  ggplot(aes(x = prcp, fill=name))+
  geom_density(alpha=0.3)+
  theme(legend.position="none")
ggp_tmax_date=
  weather_df%>%
  ggplot(aes(x = date, y = tmax,color=name))+
  geom_point()+
  geom_smooth()+
  theme(legend.position="bottom")
(ggp_tmax_tmin+ggp_prcp_dens)/ggp_tmax_date
```

## data manipulation
quick example on factors
```{r}
weather_df%>%
  mutate(
    name=fct_reorder(name,tmax)
  )%>%
  ggplot(aes(x=name,y=tmax))+
  geom_boxplot()
```


What about tmax and tmin
```{r}
weather_df%>%
  pivot_longer(
    tmax:tmin,
    names_to = "obs",
    values_to = "temperature"
  )%>%
  ggplot(aes(x=temperature, fill=obs))+
  geom_density(alpha=.3)+
  facet_grid(.~name)
```
```{r}
getwd()
```


```{r}
pulse_df=
  haven::read_sas("./data_import_examples-2/public_pulse_data.sas7bdat")%>%
  janitor::clean_names()%>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi",
    names_prefix = "bdi_score_"
  )%>%
  mutate(visit=recode(visit,"bl"="00m"))
pulse_df%>%
  ggplot(aes(x=visit,y=bdi))+
  geom_boxplot()


```
```{r}
pulse_df%>%
  ggplot(aes(x=visit,y=bdi))+
  geom_point(size=0.2)+
  geom_line(aes(group=id),alpha=.2)

```


