---
title: "Visualization with ggplot2"
author: "Shengzhi Luo"
date: "05/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width=6,
  fig.asp=6,
  out.width = "90%",
  echo = TRUE)
```
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_df
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```
```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

## Use a sata manipilation as part of this 

```{r,include=FALSE}
weather_df %>%
  filter(name="CentralPark_NY") %>%
  mutate(
    tmax=tmax*(9/5)+32,
    tmin=tmin*(9/5)+32
  )%>%
  ggplot(aes())
```

## Stacking geoms

Which geoms do oun wnat

```{r}
weather_df%>%
  ggplot(aes(x = date, y = tmax, color = name))+
  geom_smooth()
```

```{r}
weather_df%>%
  ggplot(aes(x = tmin, y = tmax))+
  geom_hex()
```

```{r}
weather_df%>%
  ggplot(aes(x = tmin, y = tmax))+
  geom_bin_2d()
```

## Univariate plots
```{r}
weather_df%>%
  ggplot(aes(x = tmax)) +
  geom_histogram()
  
```



```{r}
weather_df%>%
  ggplot(aes(x = tmax, fill=name))+
  geom_density(alpha=.3)
```


```{r}
weather_df %>%
  ggplot(aes(x=name,y=tmax)) +
  geom_boxplot()

```
```{r}
weather_df%>%
  ggplot(aes(x=tmax,y=name))+
  geom_violin()
```
```{r}
weather_df %>%
  ggplot(aes(x=tmax,y=name))+
  geom_density_ridges(alpha=0.8,sacle=0.8)
```


```{r}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)
```

```{r,fig.width=6}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)
```


# ggplot pt.2
```{r}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax))+
  geom_point(aes(color=name))
```

